# Generated by Django 2.1.5 on 2019-02-25 02:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Maker',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='名称')),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qr', models.CharField(max_length=100, unique=True, verbose_name='QRコード')),
                ('name', models.CharField(max_length=100, verbose_name='食品名')),
                ('height', models.FloatField(verbose_name='サイズ(高さ)')),
                ('width', models.FloatField(verbose_name='サイズ(幅)')),
                ('qr_at_height', models.FloatField(verbose_name='QR位置(横)')),
                ('maker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.Maker', verbose_name='メーカ')),
            ],
        ),
    ]
