# Generated by Django 2.1.5 on 2019-05-06 08:06

from django.db import migrations, models
import django.db.models.deletion
import unixtimestampfield.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='History',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cooked_at', unixtimestampfield.fields.UnixTimeStampField(verbose_name='調理完了日時')),
                ('power_consumed', models.FloatField(verbose_name='消費電力')),
                ('other_info', models.TextField(verbose_name='付加情報')),
            ],
            options={
                'verbose_name': '調理履歴',
                'verbose_name_plural': '調理履歴',
            },
        ),
        migrations.CreateModel(
            name='HistoryByChannel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('channel', models.IntegerField(verbose_name='チャネル')),
                ('surf_temp_before', models.FloatField(verbose_name='開始表面温度')),
                ('surf_temp_after', models.FloatField(verbose_name='終了表面温度')),
                ('seconds_taken', models.IntegerField(verbose_name='調理時間')),
                ('history', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.History', verbose_name='調理履歴')),
            ],
            options={
                'verbose_name': 'チャネル毎調理履歴',
                'verbose_name_plural': 'チャネル毎調理履歴',
            },
        ),
        migrations.CreateModel(
            name='Maker',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='名称')),
            ],
            options={
                'verbose_name': '電子レンジメーカ',
                'verbose_name_plural': '電子レンジメーカ',
            },
        ),
        migrations.CreateModel(
            name='Oven',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=255, unique=True, verbose_name='機種コード')),
                ('maker_name', models.CharField(max_length=100, verbose_name='メーカ')),
                ('model_name', models.CharField(max_length=100, verbose_name='機種名')),
                ('floor_width_in_mm', models.IntegerField(verbose_name='底面幅')),
                ('floor_height_in_mm', models.IntegerField(verbose_name='底面高さ')),
                ('channel_info', models.CharField(max_length=255, verbose_name='チャネル情報')),
            ],
            options={
                'verbose_name': '電子レンジ機種',
                'verbose_name_plural': '電子レンジ機種',
            },
        ),
        migrations.CreateModel(
            name='OvenChannel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seq', models.IntegerField(verbose_name='チャネル番号')),
                ('x_offset_mm', models.FloatField(verbose_name='水平方向オフセット(mm)')),
                ('y_offset_mm', models.FloatField(verbose_name='垂直方向オフセット(mm)')),
                ('width_in_mm', models.FloatField(verbose_name='幅(mm)')),
                ('height_in_mm', models.FloatField(verbose_name='高さ(mm)')),
                ('oven', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='channels', to='backend.Oven', verbose_name='レンジ')),
            ],
            options={
                'verbose_name': 'チャネル',
                'verbose_name_plural': 'チャネル',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qr', models.CharField(max_length=255, unique=True, verbose_name='qr')),
                ('name', models.CharField(max_length=100, verbose_name='食品名')),
                ('manufacturer', models.CharField(blank=True, max_length=255, null=True, verbose_name='製造元')),
                ('seller', models.CharField(blank=True, max_length=255, null=True, verbose_name='販売元')),
                ('ingredients', models.CharField(blank=True, max_length=255, null=True, verbose_name='原材料')),
                ('allergens', models.CharField(blank=True, max_length=255, null=True, verbose_name='アレルゲン')),
                ('calory', models.FloatField(blank=True, null=True, verbose_name='カロリー')),
                ('height', models.FloatField(verbose_name='サイズ(高さ)')),
                ('width', models.FloatField(verbose_name='サイズ(幅)')),
                ('qr_at_height', models.FloatField(verbose_name='QR位置(縦)')),
                ('qr_at_width', models.FloatField(verbose_name='QR位置(横)')),
                ('other_info', models.CharField(max_length=255, verbose_name='付加情報')),
            ],
            options={
                'verbose_name': '食品',
                'verbose_name_plural': '食品',
            },
        ),
        migrations.CreateModel(
            name='Recipe',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='レシピ名')),
                ('recipe', models.CharField(max_length=255, verbose_name='レシピ')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.Product', verbose_name='商品')),
            ],
            options={
                'verbose_name': 'レシピ',
                'verbose_name_plural': 'レシピ',
            },
        ),
        migrations.CreateModel(
            name='RecipeQuery',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='from_microwaves/', verbose_name='画像')),
                ('received_at', unixtimestampfield.fields.UnixTimeStampField(auto_now_add=True, verbose_name='問い合わせ日時')),
                ('oven', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.Oven', verbose_name='機種')),
            ],
            options={
                'verbose_name': 'レシピ検索履歴',
                'verbose_name_plural': 'レシピ検索履歴',
            },
        ),
        migrations.AddField(
            model_name='historybychannel',
            name='recipe',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.Recipe', verbose_name='利用レシピ'),
        ),
        migrations.AddField(
            model_name='history',
            name='corresponding_query',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.RecipeQuery', verbose_name='問い合わせ'),
        ),
    ]
