# Generated by Django 2.1.5 on 2019-03-03 11:13

from django.db import migrations, models
import django.db.models.deletion
import unixtimestampfield.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Maker',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='名称')),
            ],
            options={
                'verbose_name': '電子レンジメーカ',
                'verbose_name_plural': '電子レンジメーカ',
            },
        ),
        migrations.CreateModel(
            name='Oven',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('oven_code', models.CharField(max_length=255, unique=True, verbose_name='機種コード')),
                ('maker_name', models.CharField(max_length=100, verbose_name='メーカ')),
                ('model_name', models.CharField(max_length=100, verbose_name='機種名')),
                ('floor_width_in_cm', models.IntegerField(verbose_name='底面幅')),
                ('floor_height_in_cm', models.IntegerField(verbose_name='底面高さ')),
                ('channel_info', models.CharField(max_length=255, verbose_name='チャネル情報')),
            ],
            options={
                'verbose_name': '電子レンジ機種',
                'verbose_name_plural': '電子レンジ機種',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jan', models.CharField(max_length=13, verbose_name='jan')),
                ('version', models.CharField(max_length=10, verbose_name='バージョン')),
                ('name', models.CharField(max_length=100, verbose_name='食品名')),
                ('height', models.FloatField(verbose_name='サイズ(高さ)')),
                ('width', models.FloatField(verbose_name='サイズ(幅)')),
                ('qr_at_height', models.FloatField(verbose_name='QR位置(縦)')),
                ('qr_at_width', models.FloatField(verbose_name='QR位置(横)')),
                ('info', models.CharField(max_length=255, verbose_name='付加情報')),
            ],
            options={
                'verbose_name': '食品',
                'verbose_name_plural': '食品',
            },
        ),
        migrations.CreateModel(
            name='Recipe',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='レシピ名')),
                ('recipe', models.CharField(max_length=255, verbose_name='レシピ')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.Product', verbose_name='商品')),
            ],
            options={
                'verbose_name': 'レシピ',
                'verbose_name_plural': 'レシピ',
            },
        ),
        migrations.CreateModel(
            name='RecipeQuery',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='from_microwaves/', verbose_name='画像')),
                ('received_at', unixtimestampfield.fields.UnixTimeStampField(auto_now_add=True, verbose_name='問い合わせ日時')),
                ('oven', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.Oven', verbose_name='機種')),
            ],
            options={
                'verbose_name': 'レシピ検索履歴',
                'verbose_name_plural': 'レシピ検索履歴',
            },
        ),
    ]
