# Generated by Django 2.1.5 on 2019-05-06 08:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ovenchannel',
            old_name='x_offset_mm',
            new_name='x_offset_in_mm',
        ),
        migrations.RenameField(
            model_name='ovenchannel',
            old_name='y_offset_mm',
            new_name='y_offset_in_mm',
        ),
    ]
