# Generated by Django 2.1.5 on 2019-02-25 03:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0002_auto_20190225_1204'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='maker',
        ),
    ]
