# Generated by Django 2.1.5 on 2019-05-06 08:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0002_auto_20190506_1709'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='oven',
            name='channel_info',
        ),
    ]
