# Generated by Django 2.1.5 on 2019-03-04 00:59

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0002_auto_20190303_1127'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='qr',
            field=models.CharField(default=django.utils.timezone.now, max_length=255, unique=True, verbose_name='qr'),
            preserve_default=False,
        ),
    ]
