# Generated by Django 2.1.5 on 2019-05-06 08:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0003_remove_oven_channel_info'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='qr_at_height',
            new_name='qr_x_offset_in_mm',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='qr_at_width',
            new_name='qr_y_offset_in_mm',
        ),
        migrations.AlterField(
            model_name='history',
            name='other_info',
            field=models.TextField(blank=True, null=True, verbose_name='付加情報'),
        ),
    ]
