# Generated by Django 2.1.5 on 2019-03-04 01:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0003_product_qr'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='jan',
        ),
        migrations.RemoveField(
            model_name='product',
            name='version',
        ),
        migrations.AddField(
            model_name='product',
            name='allergens',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='アレルゲン'),
        ),
        migrations.AddField(
            model_name='product',
            name='calory',
            field=models.FloatField(blank=True, null=True, verbose_name='カロリー'),
        ),
        migrations.AddField(
            model_name='product',
            name='ingredients',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='原材料'),
        ),
        migrations.AddField(
            model_name='product',
            name='manufacturer',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='製造元'),
        ),
        migrations.AddField(
            model_name='product',
            name='other_info',
            field=models.CharField(default=1, max_length=255, verbose_name='付加情報'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='product',
            name='seller',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='販売元'),
        ),
    ]
