# Generated by Django 2.1.5 on 2019-03-04 01:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0004_auto_20190304_1008'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='code',
            field=models.CharField(default='001', max_length=255, unique=True, verbose_name='レシピID'),
        ),
    ]
