# Generated by Django 2.1.5 on 2019-05-06 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0004_auto_20190506_1718'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='height',
        ),
        migrations.RemoveField(
            model_name='product',
            name='width',
        ),
        migrations.AddField(
            model_name='product',
            name='height_in_mm',
            field=models.FloatField(default=1, verbose_name='高さ(mm)'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='product',
            name='width_in_mm',
            field=models.FloatField(default=1, verbose_name='幅(mm)'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='product',
            name='qr_x_offset_in_mm',
            field=models.FloatField(verbose_name='QR位置-x(mm)'),
        ),
        migrations.AlterField(
            model_name='product',
            name='qr_y_offset_in_mm',
            field=models.FloatField(verbose_name='QR位置-y(mm)'),
        ),
    ]
