# Generated by Django 2.1.5 on 2019-03-04 07:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0005_recipe_code'),
    ]

    operations = [
        migrations.RenameField(
            model_name='oven',
            old_name='floor_height_in_cm',
            new_name='floor_height_in_mm',
        ),
        migrations.RenameField(
            model_name='oven',
            old_name='floor_width_in_cm',
            new_name='floor_width_in_mm',
        ),
        migrations.RemoveField(
            model_name='recipe',
            name='code',
        ),
    ]
