# Generated by Django 2.1.5 on 2019-02-27 04:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0005_auto_20190227_1323'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipequery',
            name='channels',
            field=models.CharField(default=1, max_length=255, verbose_name='庫内情報'),
            preserve_default=False,
        ),
    ]
