# Generated by Django 2.1.5 on 2019-05-31 06:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='other_info',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='付加情報'),
        ),
    ]
