# Generated by Django 2.1.5 on 2019-05-31 07:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_uploadedfile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='uploadedfile',
            name='content',
        ),
    ]
