# Generated by Django 2.1.5 on 2019-05-31 07:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_remove_uploadedfile_content'),
    ]

    operations = [
        migrations.CreateModel(
            name='UploadedErrorRecord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason', models.CharField(max_length=255, verbose_name='エラー事由')),
                ('file', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.UploadedFile', verbose_name='ファイル')),
            ],
            options={
                'verbose_name': 'アップロードファイル',
                'verbose_name_plural': 'アップロードファイル',
            },
        ),
    ]
