# Generated by Django 2.1.5 on 2019-06-03 05:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_uploadederrorrecord'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='uploadederrorrecord',
            options={'verbose_name': 'アップロードエラー', 'verbose_name_plural': 'アップロードエラー'},
        ),
    ]
