# Generated by Django 2.1.5 on 2019-06-04 01:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_auto_20190604_1012'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='other_info',
            new_name='otherInfo',
        ),
    ]
