# Generated by Django 2.1.5 on 2019-06-05 00:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_auto_20190604_1014'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='oven',
            options={'verbose_name': '1.電子レンジ機種', 'verbose_name_plural': '1.電子レンジ機種'},
        ),
        migrations.AlterModelOptions(
            name='ovenchannel',
            options={'verbose_name': '2.チャネル', 'verbose_name_plural': '2.チャネル'},
        ),
        migrations.AlterModelOptions(
            name='product',
            options={'verbose_name': '3.食品', 'verbose_name_plural': '3.食品'},
        ),
        migrations.AlterModelOptions(
            name='recipe',
            options={'verbose_name': '4.レシピ', 'verbose_name_plural': '4.レシピ'},
        ),
        migrations.AlterModelOptions(
            name='uploadederrorrecord',
            options={'verbose_name': '5.食品/レシピ一括登録エラー', 'verbose_name_plural': '5.食品/レシピ一括登録エラー'},
        ),
        migrations.AlterModelOptions(
            name='uploadedfile',
            options={'verbose_name': '6.食品/レシピ一括登録', 'verbose_name_plural': '6.食品/レシピ一括登録'},
        ),
        migrations.AlterField(
            model_name='oven',
            name='floor_height_in_mm',
            field=models.IntegerField(verbose_name='底面高さ(mm)'),
        ),
        migrations.AlterField(
            model_name='oven',
            name='floor_width_in_mm',
            field=models.IntegerField(verbose_name='底面幅(mm)'),
        ),
    ]
