# Generated by Django 2.1.5 on 2019-06-07 03:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_auto_20190605_0907'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='uploadederrorrecord',
            options={'verbose_name': '6.食品/レシピ一括登録エラー', 'verbose_name_plural': '6.食品/レシピ一括登録エラー'},
        ),
        migrations.AlterModelOptions(
            name='uploadedfile',
            options={'verbose_name': '5.食品/レシピ一括登録', 'verbose_name_plural': '5.食品/レシピ一括登録'},
        ),
    ]
